### ISSUE TITLE
Sitzungen ohne Dokumente funktionieren so nicht

### ISSUE THREAD

**Issue by astro** [offenesdresden/ratsinfo-scraper#14]
Bei denen gibts kein `.zip`. Beispiel: http://ratsinfo.dresden.de/to0040.php?__ksinr=2040

WIr müssten das HTML gleich scrapen, dabei am besten den Download der PDFs weglassen. Das kann jeder, in ihnen wird nicht gescraped, sie fressen nur Plattenplatz.

**Comment by Mic92** [comment]
damals war die Dokumentenstruktur in den ZIP-Archiven konsistenter und stabiler.
